package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.TopUpBalancePojo;
import org.testng.annotations.Test;

import javax.ws.rs.BadRequestException;

public class TopUpBalanceTest implements TestInterface {
    private CustomerPojo customerPojo;
    private AccountTokenPojo accountTokenPojo;
    @Test(description = "Top up balance.")
    @Severity(SeverityLevel.CRITICAL)
    @Feature("Top up balance feature.")
    public void topUpBalanceTest(){
        customerPojo = client.createAutoGeneratedCustomer(adminToken);
        accountTokenPojo = client.authenticate(customerPojo.login, customerPojo.pass);
        TopUpBalancePojo top = client.fillTopUpBalancePojo(customerPojo);
        client.topUpBalance(accountTokenPojo, top);
    }

    @Test(description = "Wrong top up balance.", dependsOnMethods = "topUpBalanceTest",expectedExceptions = BadRequestException.class)
    @Severity(SeverityLevel.CRITICAL)
    @Feature("Top up balance feature.")
    public void wrongTopUpBalanceTest(){
        TopUpBalancePojo top = client.fillTopUpBalancePojo(customerPojo);
        top.money = -1000;
        client.topUpBalance(accountTokenPojo, top);
    }
}
